# Generated by Django 3.2.9 on 2021-11-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(max_length=15)),
                ('from_branch', models.TextField(max_length=10)),
                ('to_branch', models.TextField(max_length=10)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
