# Generated by Django 3.2.9 on 2021-11-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='open',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repo',
            field=models.TextField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='title',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
