# Generated by Django 3.2.9 on 2021-11-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20211106_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='created_by',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='from_branch',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='repo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='to_branch',
            field=models.TextField(),
        ),
    ]
