# Generated by Django 3.2.9 on 2021-11-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20211107_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='sha',
            field=models.TextField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
